version: '3'
services:
  mysql:
    image: mysql:5.5
    network_mode: host
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASENAME: matchdb
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672

  usercricservice:
    image: userservice
    build: userservice/
    restart: always
    network_mode: host
    depends_on:
      - eurekaserver
      - mysql
    ports:
      - 8089:8089
    healthcheck:
      test: "exit 0"

  favoriteservice:
    image: favouriteservice
    build: favouriteservice/
    restart: always
    network_mode: host
    depends_on:
      - eurekaserver
      - mysql
      - rabbitmq
    ports:
      - 8090:8090
    healthcheck:
      test: "exit 0"

  playerrecommendationservice:
    image: playerrecommendationservice
    build: matchrecommendationservice/
    restart: always
    network_mode: host
    depends_on:
      - eurekaserver
      - mysql
      - rabbitmq
    ports:
      - 8091:8091
    healthcheck:
      test: "exit 0"

  eurekaserver:
    image: eurekaserver
    build: eurekaserverdemo/
    restart: always
    network_mode: host
    ports:
      - 9003:9003
    healthcheck:
      test: "exit 0"

  criczuulservice:
    image: criczuulservice
    build: zuulservice/
    restart: always
    network_mode: host
    ports:
      - 8086:8086
    healthcheck:
      test: "exit 0"

  cricui:
    image: cricui
    build: CMatchesUI/
    network_mode: host
    container_name: angular-docker
    ports:
      - 8080:8080
    healthcheck:
      test: "exit 0"