spring:
  application:
    name: userservice
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
   hibernate:
    ddl-auto: update
   show-sql: true
server:
 port: 8089



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9003/eureka

#spring:
#  application:
#    name: userservice
#  datasource:
#    url: jdbc:mysql://localhost:3306/matchdb
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#server:
#  port: 8089